server:
  servlet:
    contextPath: /hexadzoho

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
#  file : log/application.log
  level :
    org:
      springframework:
        web : DEBUG
      hibernate: ERROR
